version: '3.9'

services:
  application-db:
    image: postgres:alpine
    networks:
      - application-db
    volumes:
      - ./data/postgres:/data/postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=applicationdb
    ports:
      - 5432:5432

  application-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '4005:4005'
    depends_on:
      - application-db
    networks:
      - application-db

networks:
  application-db:
    driver: bridge